productly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("products/", include("products.urls")),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("", views.index, name="products"),
    path("<int:product_id>", views.detail, name="product_detail"),
    path("add_product", views.add_product, name="add_product")
]

products/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=255)
    stock = models.IntegerField()
    score = models.FloatField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name
    

products/forms.py
from . import models
from django import forms

class ProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['name', 'stock', 'score', 'category']

        error_messages = {
            'name': {
                'required': 'Please enter your name'
            },
            'stock': {
                'required': 'Please enter the stock'
            },
            'score': {
                'required': 'Please enter the score'
            },
            'category': {
                'required': 'Please enter the category'
            }
        }
        

productly/views.py
from django.shortcuts import render

def index(request):
    return render(
        request, 'index.html'
    )

products/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .forms import ProductForm 
from .models import Product

# Create your views here.
def index(request):
    products = Product.objects.all()

    return render(
        request, 'products.html', context={
            'products': products
        }
    )


def detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'detail.html', context={
        'product': product
    })

def add_product(request):
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/products")
    else:
        form = ProductForm()
    return render(
        request, 'add_product.html', {
        'product_form': form})

products/templates/add_product.html
{% extends "base.html" %}

{% block title %}
    <title>Add New Product</title>
{% endblock title %}

{% block content %}
    <main class="container-fluid g-0">
        <section class="row">
            <article class="col-6">
                <form novalidate class="form-control" action="{% url "products:add_product" %}" method="POST">
                    {% csrf_token %}
                    {{ product_form }}
                    <input type="submit">
                </form>
            </article>
        </section>
    </main>
{% endblock content %}

products/templates/detail.html
{% extends "base.html" %}
{% block title %}
    <title>Detalle del producto {{ product }}</title>
{% endblock title %}

{% block content %}
    <main class="container-fluid g-0 text-center">
        <h6>{{ product.name }}</h6>
        <p>{{ product.stock }}</p>
        <p>{{ product.score }}</p>
        <p>{{ product.created_at }}</p>
        <p>{{ product.category }}</p>
    </main>
{% endblock content %}

products/templates/index.html
{% extends "base.html" %}

{% block title %}
    <title>Products</title>
{% endblock title %}
{% block content %}
    <main class="container-fluid g-0">
        <section class="col-6">
            <h1>Products</h1>
            <table class="table table-striped table-dark">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Stock</th>
                        <th>Created at</th>
                        <th>Category</th>
                    </tr>
                </thead>
                <tbody>
                    {% if products %}
                        {% for product in products %}
                            <tr>
                                <td><a href="{% url "products:product_detail" product.id %}">{{ product.name }}</a></td>
                                <td>{{ product.stock }}</td>
                                <td>{{ product.created_at }}</td>
                                <td>{{ product.category }}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </section>
    </main>
{% endblock content %}

products/templates/products.html
{% extends "base.html" %}

{% block title %}
    <title>Products</title>
{% endblock title %}
{% block content %}
    <main class="container-fluid g-0">
        <section class="col-6">
            <h1>Products</h1>
            <a href="{% url "products:add_product" %}" class="btn btn-primary">Add product</a>
            <table class="table table-striped table-dark">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Stock</th>
                        <th>Created at</th>
                        <th>Category</th>
                    </tr>
                </thead>
                <tbody>
                    {% if products %}
                        {% for product in products %}
                            <tr>
                                <td><a href="{% url "products:product_detail" product.id %}">{{ product.name }}</a></td>
                                <td>{{ product.stock }}</td>
                                <td>{{ product.created_at }}</td>
                                <td>{{ product.category }}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </section>
    </main>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock title %}
    {% load bootstrap5 %}

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
</head>
<body>
    {% include "nav.html" %}
    {% block content %}

    {% endblock content %}
</body>
</html>

templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %} class="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

templates/django/forms/widgets/attrs.html
{% for name, value in widget.attrs.items %}
    {% if value is not False %} 
        {{ name }}
        {% if value is not True %}="{{ value|stringformat:'s' }}"
        {% endif %}
    {% endif %}
{% endfor %}

templates/django/forms/widgets/input.html
<input 
    class="form-control {{ widget.attrs.class}}"
    type="{{ widget.type }}" 
    name="{{ widget.name }}"{% if widget.value != None %} 
    value="{{ widget.value|stringformat:'s' }}"{% endif %}{% include "django/forms/widgets/attrs.html" %}>

templates/django/forms/widgets/select.html
<select class="form-select {{ widget.attrs.class}}" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
  <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
  {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
  </optgroup>{% endif %}{% endfor %}
</select>

templates/form_snippet.html
{% load add_attr %}

{% for field in form %}
    <div class="mb-3">
        {{ field.label_tag }}
        {% if field.errors %}
            {{ field|add_attr:"class:is-invalid" }}
        {% else %}
            {{ field }}
        {% endif %}
        <div  class="invalid-feedback">
            {% for error in field.errors %}
                {{ error }}
            {% endfor %}
        </div>
    </div>
{% endfor %}

templates/index.html
{% extends "base.html" %}

{% block title %}
    <title>Home</title>
{% endblock title %}

{% block content %}
    <main class="container-fluid">
        <h1>Bienvenido a Productly!</h1>
    </main>
{% endblock content %}

templates/nav.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "index" %}">Productly</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "index" %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "products:products" %}">Products</a>
        </li>
      </ul>
    </div>
  </div>
</nav>